server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-order
    jdbc-url: jdbc:postgresql://localhost:5432/db-order
    username: postgres
    password: testDB12
    driver-class-name: org.postgresql.Driver

  application:
    name: "estudo-jdbi"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html