server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-order
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

# springdoc (opcional customizações)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html